// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB9r7Ve0nP5UgZz6P0Pptmp5pgxI5KDOQ',
    appId: '1:49317886540:web:91278f14ae5116cd0212e9',
    messagingSenderId: '49317886540',
    projectId: 'rakeb-2753f',
    authDomain: 'rakeb-2753f.firebaseapp.com',
    storageBucket: 'rakeb-2753f.firebasestorage.app',
    measurementId: 'G-9LFKFVXFCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCebicGg03rrU-47F77be_xtrXWHp3WOG0',
    appId: '1:49317886540:android:76aa3b5cdc515e480212e9',
    messagingSenderId: '49317886540',
    projectId: 'rakeb-2753f',
    storageBucket: 'rakeb-2753f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBerAU2P5Mv57HyVQhr4v_NXtzF3tWk1OE',
    appId: '1:49317886540:ios:3dabce083a144ab30212e9',
    messagingSenderId: '49317886540',
    projectId: 'rakeb-2753f',
    storageBucket: 'rakeb-2753f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBerAU2P5Mv57HyVQhr4v_NXtzF3tWk1OE',
    appId: '1:49317886540:ios:3dabce083a144ab30212e9',
    messagingSenderId: '49317886540',
    projectId: 'rakeb-2753f',
    storageBucket: 'rakeb-2753f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB9r7Ve0nP5UgZz6P0Pptmp5pgxI5KDOQ',
    appId: '1:49317886540:web:d4e735063f79949e0212e9',
    messagingSenderId: '49317886540',
    projectId: 'rakeb-2753f',
    authDomain: 'rakeb-2753f.firebaseapp.com',
    storageBucket: 'rakeb-2753f.firebasestorage.app',
    measurementId: 'G-0VPCMDE7J4',
  );
}
